[package]
name = "openai-proxy"
version = "0.1.0"
edition = '2021'

[dependencies]
actix-web = "4.0"
reqwest = { version = "0.11", features = ["json"] }
reqwest-eventsource = "0.4"
serde_json = "1.0"
futures = "0.3"