# fly.toml app configuration file generated for fully-cacheable on 2024-07-17T15:37:22+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fully-cacheable'
primary_region = 'cdg'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 4567
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "litefs"
  destination = "/var/lib/litefs"

